# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
    initrd.kernelModules = [ "kvm-intel" "wl" ];
    kernelModules = [ "kvm-intel" "wl" ];
    extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];
    kernelPackages = pkgs.linuxPackages;
  };


  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/7dca3398-8f56-4cd0-803b-637ccec065b9";
      fsType = "btrfs";
      options = [ "subvol=root" "compress-force=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/7dca3398-8f56-4cd0-803b-637ccec065b9";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/7dca3398-8f56-4cd0-803b-637ccec065b9";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/6CFA-BCAF";
      fsType = "vfat";
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
