hosts = [
  "hastur", # homeserver censored
  "nodens", # digital ocean sf
  "kaambl", # laptop
  "abhoth", # vmiss
  "azasos", # tencent cloud censored
  "eihort", # nas
  # "bootstrap",
  # "resq",
  # "yidhra", # aws lightsail
  # "colour"  # colour
]
