# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      systemd.enable = true;
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ "tpm" "tpm_tis" "tpm_crb" "kvm-amd" ];
    };
    kernelModules = [ "ec_sys" "uhid" "kvm-amd" ];
    extraModulePackages = with config.boot.kernelPackages; [ v4l2loopback ];
    kernelPackages = pkgs.linuxPackages_latest;
    # binfmt.emulatedSystems = [
    #   "riscv64-linux"
    #   "aarch64-linux"
    #   "mips64el-linux"
    #   "mipsel-linux"
    # ];
    kernelParams = [
      "amd_pstate=active"
      "amd_iommu=on"
      # "iommu=pt"
      "random.trust_cpu=off"
      "zswap.enabled=1"
      "zswap.compressor=lz4"
      "zswap.zpool=zsmalloc"

      # "amdgpu.noretry=0"
      # "amdgpu.lockup_timeout=1000"
      # "amdgpu.gpu_recovery=1"
      # "amdgpu.audio=0"
    ];
  };


  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=4G" "mode=755" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/e86a6cfa-39cc-4dd9-b5d3-fee5e2613578";
    fsType = "btrfs";
    options = [ "subvol=/persist" "compress-force=zstd" "noatime" "discard=async" "space_cache=v2" ];
    neededForBoot = true;
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/e86a6cfa-39cc-4dd9-b5d3-fee5e2613578";
    fsType = "btrfs";
    options = [ "subvol=/nix" "compress-force=zstd" "noatime" "discard=async" "space_cache=v2" ];
  };


  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/e86a6cfa-39cc-4dd9-b5d3-fee5e2613578";
    fsType = "btrfs";
    options = [ "subvol=/var" "compress-force=zstd" "noatime" "discard=async" "space_cache=v2" ];
  };

  # fileSystems."/tmp" = {
  #   device = "/dev/disk/by-uuid/e86a6cfa-39cc-4dd9-b5d3-fee5e2613578";
  #   fsType = "btrfs";
  #   options = [ "subvolid=28831" "compress-force=zstd" "noatime" "discard=async" "space_cache=v2" ];
  # };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/3418-1C5E";
    fsType = "vfat";
  };

  swapDevices = [{
    device = "/dev/disk/by-partuuid/67a00700-d210-4dbf-a02d-bfefbf6a9a72";
    randomEncryption = {
      enable = true;
      cipher = "aes-xts-plain64";
      source = "/dev/random";
    };
  }];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
