auto_sync = true
dialect = "us"
filter_mode = "global"
filter_mode_shell_up_key_binding = "directory"
key_path = "/run/agenix/atuin_key"
search_mode = "fuzzy"
sync_address = "https://api.atuin.nyaw.xyz"
sync_frequency = "10m"

[sync]
record = true
