name: sensitive check
on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  check-sensitive:
    name: key material check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: detect
        shell: bash
        run: |
          #!/bin/bash
          materials=("AGE-SECRET-KEY" "BEGIN OPENSSH PRIVATE KEY" "BEGIN PGP PRIVATE KEY BLOCK" "PRIVATE")
          
          for per in "${materials[@]}"
          do
            [ -z "$(grep -r "$per" --exclude="sensitive.yaml" ./)" ] || exit 1
          done
