name: "Sync nixos-config repo"
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    # same as build ci
    - cron:  '13 10 * * *'


jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      if: github.repository == 'oluceps/nur-pkgs'
      with:
        source_repo: "https://github.com/oluceps/nixos-config"
        source_branch: "trival"
        destination_branch: "master"
        github_token: ${{ secrets.PAT }}
